---
# Namespace for scheduled traffic generation
apiVersion: v1
kind: Namespace
metadata:
  name: nat-gateway-test

---
# ServiceAccount for CronJob
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-generator
  namespace: nat-gateway-test

---
# ClusterRole for managing pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-generator
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traffic-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traffic-generator
subjects:
- kind: ServiceAccount
  name: traffic-generator
  namespace: nat-gateway-test

---
# CronJob to start traffic generators (runs at minute 0 of every hour)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-traffic-generator
  namespace: nat-gateway-test
spec:
  # Run at minute 0 of every hour (00:00, 01:00, 02:00, etc.)
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: traffic-generator
          containers:
          - name: scaler
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting traffic generators..."
              kubectl scale deployment http-traffic-generator -n nat-gateway-test --replicas=2
              kubectl scale deployment dns-traffic-generator -n nat-gateway-test --replicas=2
              kubectl scale deployment tcp-traffic-generator -n nat-gateway-test --replicas=1
              echo "Traffic generators started"
          restartPolicy: OnFailure

---
# CronJob to stop traffic generators (runs at minute 5 of every hour)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: stop-traffic-generator
  namespace: nat-gateway-test
spec:
  # Run at minute 5 of every hour (00:05, 01:05, 02:05, etc.)
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: traffic-generator
          containers:
          - name: scaler
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Stopping traffic generators..."
              kubectl scale deployment http-traffic-generator -n nat-gateway-test --replicas=0
              kubectl scale deployment dns-traffic-generator -n nat-gateway-test --replicas=0
              kubectl scale deployment tcp-traffic-generator -n nat-gateway-test --replicas=0
              echo "Traffic generators stopped"
          restartPolicy: OnFailure

---
# HTTP Traffic Generator Deployment (starts with 0 replicas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-traffic-generator
  namespace: nat-gateway-test
  labels:
    app: http-traffic-generator
spec:
  replicas: 0
  selector:
    matchLabels:
      app: http-traffic-generator
  template:
    metadata:
      labels:
        app: http-traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Starting HTTP traffic generation..."
            while true; do
              curl -s -m 5 https://www.google.com > /dev/null 2>&1
              curl -s -m 5 https://www.amazon.com > /dev/null 2>&1
              curl -s -m 5 https://www.github.com > /dev/null 2>&1
              curl -s -m 5 https://www.cloudflare.com > /dev/null 2>&1
              curl -s -m 5 https://www.wikipedia.org > /dev/null 2>&1
              sleep $((RANDOM % 5 + 1))
            done
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      restartPolicy: Always

---
# DNS Traffic Generator Deployment (starts with 0 replicas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-traffic-generator
  namespace: nat-gateway-test
  labels:
    app: dns-traffic-generator
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dns-traffic-generator
  template:
    metadata:
      labels:
        app: dns-traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: alpine:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            apk add --no-cache bind-tools
            echo "Starting DNS traffic generation..."
            DOMAINS="google.com amazon.com github.com cloudflare.com aws.amazon.com kubernetes.io docker.com"
            while true; do
              for domain in $DOMAINS; do
                nslookup "$domain" > /dev/null 2>&1
                sleep 1
              done
            done
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      restartPolicy: Always

---
# TCP Traffic Generator Deployment (starts with 0 replicas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-traffic-generator
  namespace: nat-gateway-test
  labels:
    app: tcp-traffic-generator
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tcp-traffic-generator
  template:
    metadata:
      labels:
        app: tcp-traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: alpine:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Starting TCP traffic generation..."
            while true; do
              timeout 5 sh -c 'cat < /dev/null > /dev/tcp/8.8.8.8/53' 2>/dev/null
              timeout 5 sh -c 'cat < /dev/null > /dev/tcp/1.1.1.1/443' 2>/dev/null
              timeout 5 sh -c 'cat < /dev/null > /dev/tcp/208.67.222.222/443' 2>/dev/null
              sleep 3
            done
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      restartPolicy: Always
